// Ici on stocke toutes les constantes de "nom" des mutations

export const USER_ADD = 'user/USER_ADD'
export const USER_ADD_ID = 'user/USER_ADD_ID'
export const TICKET_ADD = 'ticket/TICKET_ADD'
export const CITY_ADD = 'city/CITY_ADD'
export const CITY_ADD_ID = 'city/CITY_ADD_ID'
export const CITY_DEL_ID = 'city/CITY_DEL_ID'
export const COUNTRY_ADD = 'country/COUNTRY_ADD'
export const COUNTRY_ADD_ID = 'country/COUNTRY_ADD_ID'
export const COUNTRY_DEL_ID = 'country/COUNTRY_DEL_ID'
export const POINTING_ADD = 'pointing/POINTING_ADD'
export const POINTING_ADD_ID = 'country/POINTING_ADD_ID'
export const POINTING_DEL_ID = 'country/POINTING_DEL_ID'
export const POINTING_UPDATE_ID = 'country/POINTING_UPDATE_ID'
